#ifndef STATE_H_
#define	STATE_H_


enum StateNum {
	STATE_NOP,
	STATE_MAIN_MENU,
	STATE_LEVEL_FADEIN,
	STATE_LEVEL,
	STATE_LEVEL_FADEOUT,
	STATE_LEVEL_LOAD,
	STATE_LEVEL_PAUSED,
	STATE_LEVEL_TO_PAUSE,
	STATE_PAUSE_TO_LEVEL,
	STATE_PAUSE_TO_EXIT,
	STATE_PAUSE_FADEIN,
	STATE_GAMEOVER,
	STATE_WIN
};

extern enum StateNum state_current, state_next;

#endif